@host = http://localhost:5000

### get test
GET {{host}}/test

### drop 
POST {{host}}/drop

### post villes
POST {{host}}/addville
Content-Type: application/json

< ./src/fixtures/fakedata.json


### get reims
GET {{host}}/villes/Reims

### get villes
GET {{host}}/villes